### ISSUE TITLE
FM 87-107 wideband

### ISSUE THREAD

**Issue by nick198513** [microtony/RTLSDR-Airband#15]
Hello,

Thank you for great tool. Its amazing. I am just wondering if its possible to use it to receive normal over-the-air FM radio station channels in this band? How to make it work? If not, is there any similar alternative like yours?

**Comment by microtony** [comment]
The rtl-sdr library already contains a program, called rtl_fm, to decode wide FM.

http://sdr.osmocom.org/trac/wiki/rtl-sdr
