### ISSUE TITLE
Configuration based on sample fails to run

### ISSUE THREAD

**Issue by barjac** [microtony/RTLSDR-Airband#16]
The following config fails with:
"Configuration error: mandatory parameter missing: devices.[0].channels"

syslog = 0;

devices = (
  {
    index = 0;
    disable = false;
    gain = 28;
    mode = "scan";
    correction = 59;
    }
);
channels = (
      {
    freqs = ( 133700000, 133800000 );
    disable = false;
modulation = "am";
    afc = 0;
      }
);

I also have an "output" section, but the above fails in isolation.
Is this a bug or is something missing? I have read and re-read the sample config notes. :\
Version is 2.2.0. Running on x86_64 Mageia Linux.

**Comment by HagarViking** [comment]
You are posting this in the wrong place. 
Should be in this fork: https://github.com/szpajder/RTLSDR-Airband

I see several mistakes, but the easiest and what I'd do is copy the sample found in the config folder (in the szpajder-fork) and modify it with what you need.

**Comment by microtony** [comment]
Thanks @HagarViking .
The config you posted is for the szpajder fork that is being actively maintained. This origin is no longer maintained.
Closing this issue.

**Comment by barjac** [comment]
Thanks - sorry for the noise!
